# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: check-xml
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v1.6.1
    hooks:
      - id: verify-copyright
        name: verify-copyright
        args: [--fix, --spdx]
        files: |
          (?x)
              [.](cmake|cpp|cu|cuh|h|hpp|sh|pxd|py|pyx|rs|java)$|
              CMakeLists[.]txt$|
              CMakeLists_standalone[.]txt$|
              meta[.]yaml$|
              dependencies[.]yaml$|
              ^[.]pre-commit-config[.]yaml$
        # TODO: Re-enable once verify-codeowners supports --org parameter
        # - id: verify-codeowners
        #   args: [--fix, --org=NVIDIA, --project-prefix=cuvs-lucene]
  - repo: https://github.com/rapidsai/dependency-file-generator
    rev: v1.21.0
    hooks:
      - id: rapids-dependency-file-generator
        args: ["--clean", "--warn-all", "--strict"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        additional_dependencies: [pyyaml]
        exclude: |
          (?x)^(
            [.]github/labeler[.]yml$|
            conda/environments/.*|
            cpp/[.]clang-format$|
            cpp/[.]clang-tidy$|
            .*xfail\-.*yaml$
          )
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.28.0
    hooks:
      - id: zizmor
