# Copyright (c) 2022-2025, NVIDIA CORPORATION.

repos:
      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v5.0.0
        hooks:
              - id: check-json
              - id: trailing-whitespace
              - id: end-of-file-fixer
              - id: check-symlinks
      - repo: https://github.com/rapidsai/pre-commit-hooks
        rev: v0.6.0
        hooks:
          - id: verify-copyright
            files: |
              (?x)
                  [.](cmake|cpp|cu|cuh|h|hpp|sh|pxd|py|pyx|rs|java)$|
                  CMakeLists[.]txt$|
                  CMakeLists_standalone[.]txt$|
                  meta[.]yaml$
            exclude: |
              (?x)
                  docs/source/sphinxext/github_link\.py|
                  cpp/cmake/modules/FindAVX\.cmake
          - id: verify-alpha-spec
          - id: verify-codeowners
            args: [--fix, --project-prefix=lucene-cuvs]
      - repo: https://github.com/shellcheck-py/shellcheck-py
        rev: v0.10.0.1
        hooks:
          - id: shellcheck
