name: build
on:
  push:
    branches:
      - "main"
      - "release/*"
    tags:
      - v[0-9][0-9].[0-9][0-9].[0-9][0-9]
  workflow_dispatch:
    inputs:
      branch:
        description: |
          branch: git branch the workflow run targets.
          Required even when 'sha' is provided because it is also used for organizing artifacts.
        required: true
        type: string
      date:
        description: "date: Date (YYYY-MM-DD) this run is for. Used to organize artifacts produced by nightly builds"
        required: true
        type: string
      sha:
        description: "sha: full git commit SHA to check out"
        required: true
        type: string
      build_type:
        description: "build_type: one of [branch, nightly, pull-request]"
        type: string
        default: nightly
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
permissions: {}
jobs:
  conda-java-builds-matrix:
    permissions:
      contents: read
    uses: rapidsai/shared-workflows/.github/workflows/compute-matrix.yaml@main
    with:
      build_type: pull-request
      matrix_name: conda-cpp-build
      matrix_filter: map(select(.ARCH == "amd64"))
  java-build:
    needs: [conda-java-builds-matrix]
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@main
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.conda-java-builds-matrix.outputs.matrix) }}
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      arch: "amd64"
      date: ${{ inputs.date }}
      container_image: "rapidsai/ci-conda:26.10-cuda${{ matrix.CUDA_VER }}-${{ matrix.LINUX_VER }}-py${{ matrix.PY_VER }}"
      script: "ci/build_java.sh"
      file_to_upload: "target/"
      artifact-name: "cuvs-lucene-cuda${{ matrix.CUDA_VER }}"
      sha: ${{ inputs.sha }}
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
